[package]
name    = "vioux"
version = "0.1.0"
edition = "2021"

[lib]
# The name of the native library. This is the name which will be used in Python to import the
# library (i.e. `import vioux`)
name = "vioux"
# "cdylib" is necessary to produce a shared library for Python to import from.
# Downstream Rust code (including code in `bin/`, `examples/`, and `tests/`) will not be able
# to `use vioux;` unless the "rlib" or "lib" included
crate-type = ["cdylib", "rlib"]
#
doctest = false

[profile.dev]
lto = false

# optimize for size
[profile.release]
codegen-units = 1
panic     = "abort"
opt-level = "z"
strip     = true 
lto       = true

[features]
default     = ["desktop"]
desktop     = ["dioxus/desktop"]

[dependencies]
tonic            = "0.8.3"
prost            = "0.11.3"
anyhow           = "1.0.66"
numpy            = "0.17.2"
bytemuck         = "1.12.3"
dioxus       = { version = "0.2.4",  optional = true  }
pyo3         = { version = "0.17.3", features = ["extension-module"]  }
pyo3-asyncio = { version = "0.17", features = ["attributes", "tokio-runtime"] }
tokio        = { version = "1.23.0", features = ["macros", "rt-multi-thread"] }

[dependencies.image]
version  = "0.24.5"

[dependencies.symphonia]
version  = "0.5.1"
features = ["all"]
git = "https://github.com/pdeljanov/Symphonia"

[dev-dependencies]
md-5 = "0.10.5"

[build-dependencies]
tonic-build = "0.8.4"
