[package]
name = "vioux_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
tonic = "0.10.0"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
vioux = { path = "../vioux_lib" }

[dependencies.iced]
version = "0.10.0"
