name: cargo

on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install rust stable
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v1
      - name: install rust stable
        uses: hecrj/setup-rust-action@v1
      - name: install libv
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends ffmpeg libavutil-dev libavformat-dev libavfilter-dev libavcodec-dev libavdevice-dev libpostproc-dev libswresample-dev libswscale-dev
      - run: cargo test --no-default-features

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v1
      - name: install rust stable
        uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
      - name: install libv
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends ffmpeg libavutil-dev libavformat-dev libavfilter-dev libavcodec-dev libavdevice-dev libpostproc-dev libswresample-dev libswscale-dev
      - run: cargo clippy --no-default-features
